// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGvfFbG7Khk7AUIbvCI5c3HQCu4MDatx8',
    appId: '1:475400744672:web:b55e201aecdeabb3b6ea85',
    messagingSenderId: '475400744672',
    projectId: 'genespeluqueria-44526',
    authDomain: 'genespeluqueria-44526.firebaseapp.com',
    storageBucket: 'genespeluqueria-44526.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa1Av2oLz02I3sa2sj4X66vUT38PDe65w',
    appId: '1:475400744672:android:de57ef723c3adb78b6ea85',
    messagingSenderId: '475400744672',
    projectId: 'genespeluqueria-44526',
    storageBucket: 'genespeluqueria-44526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-7ZGpSf1CpEijxTtXKDr7hx6-RTbJwLo',
    appId: '1:475400744672:ios:15fd74f7bf637453b6ea85',
    messagingSenderId: '475400744672',
    projectId: 'genespeluqueria-44526',
    storageBucket: 'genespeluqueria-44526.appspot.com',
    iosBundleId: 'com.example.aplicacionTaller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-7ZGpSf1CpEijxTtXKDr7hx6-RTbJwLo',
    appId: '1:475400744672:ios:15fd74f7bf637453b6ea85',
    messagingSenderId: '475400744672',
    projectId: 'genespeluqueria-44526',
    storageBucket: 'genespeluqueria-44526.appspot.com',
    iosBundleId: 'com.example.aplicacionTaller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGvfFbG7Khk7AUIbvCI5c3HQCu4MDatx8',
    appId: '1:475400744672:web:c310be9146fa0c20b6ea85',
    messagingSenderId: '475400744672',
    projectId: 'genespeluqueria-44526',
    authDomain: 'genespeluqueria-44526.firebaseapp.com',
    storageBucket: 'genespeluqueria-44526.appspot.com',
  );
}
